# Generated by Django 5.2 on 2025-05-05 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id_checkin', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_checkin', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('s_nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('s_apellido', models.CharField(max_length=20)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('dv', models.CharField(max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('num_depto', models.IntegerField(unique=True)),
                ('cant_dormitorios', models.IntegerField()),
                ('cant_banos', models.IntegerField()),
                ('piso', models.IntegerField()),
                ('cant_personas', models.IntegerField()),
                ('imagen', models.CharField(blank=True, max_length=100)),
                ('valor_dia', models.IntegerField()),
                ('mantenimiento', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('s_nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('s_apellido', models.CharField(max_length=20)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('dv', models.CharField(max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('re_password', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicioAdicional',
            fields=[
                ('id_tipo_servicio_adicional', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=20)),
                ('descripcion', models.TextField(max_length=100)),
                ('valor', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id_arriendo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_checkIn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.checkin')),
            ],
        ),
        migrations.AddField(
            model_name='checkin',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.persona'),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('s_nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('s_apellido', models.CharField(max_length=20)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.persona')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalAseo',
            fields=[
                ('id_personal_aseo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('s_nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('s_apellido', models.CharField(max_length=20)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Recepcionista',
            fields=[
                ('id_recepcionista', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('s_nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('s_apellido', models.CharField(max_length=20)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('metodo_pago', models.CharField(max_length=20)),
                ('valor_pago', models.IntegerField(verbose_name=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_arriendo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.arriendo')),
                ('id_recepcionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.recepcionista')),
            ],
        ),
        migrations.AddField(
            model_name='checkin',
            name='id_recepcionista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.recepcionista'),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateField()),
                ('fecha_ingreso', models.DateField(blank=True)),
                ('fecha_salida', models.DateField()),
                ('cant_personas', models.IntegerField()),
                ('valor_total', models.FloatField()),
                ('tipo_reserva', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.cliente')),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.departamento')),
            ],
        ),
        migrations.AddField(
            model_name='checkin',
            name='id_reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.reserva'),
        ),
        migrations.CreateModel(
            name='ServicioAdicionalConsumido',
            fields=[
                ('id_servicio_adicional_consumido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_consumo', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_arreindo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.reserva')),
                ('id_tipo_servicio_adicional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.tiposervicioadicional')),
            ],
        ),
    ]
