# Generated by Django 5.2 on 2025-05-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('num_rut', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('p_nombre', models.CharField(max_length=15)),
                ('s_nombre', models.CharField(blank=True, max_length=15)),
                ('p_apellido', models.CharField(max_length=15)),
                ('s_apellido', models.CharField(blank=True, max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'ordering': ['p_nombre', 's_nombre', 'p_apellido', 's_apellido'],
            },
        ),
    ]
