# Generated by Django 5.2 on 2025-05-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='view_resumen_reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reserva', models.IntegerField()),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=10)),
                ('departamento_numero', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cantidad_de_personas', models.IntegerField()),
                ('tipo_de_reserva', models.CharField(max_length=20)),
                ('total', models.FloatField()),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'view_resumen_reserva',
                'managed': False,
            },
        ),
    ]
