# Generated by Django 5.2 on 2025-05-01 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_depto', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('num_depto', models.IntegerField(unique=True, verbose_name=3)),
                ('cant_dormitorios', models.IntegerField(verbose_name=2)),
                ('cant_banos', models.IntegerField(verbose_name=2)),
                ('piso', models.IntegerField(verbose_name=2)),
                ('cant_personas', models.IntegerField(verbose_name=2)),
                ('imagen', models.CharField(verbose_name=100)),
                ('mantenimiento', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Departamento',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('num_rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to='projects.persona')),
            ],
            options={
                'verbose_name': 'Administrador',
            },
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id_cliente', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('num_rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='projects.persona')),
            ],
            options={
                'verbose_name': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='personalAseo',
            fields=[
                ('id_personal_aseo', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('num_rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_aseo', to='projects.persona')),
            ],
            options={
                'verbose_name': 'Personal Aseo',
            },
        ),
        migrations.CreateModel(
            name='recepcionista',
            fields=[
                ('id_recepcionista', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('num_rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepcionista', to='projects.persona')),
            ],
            options={
                'verbose_name': 'Recepcionista',
            },
        ),
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id_reserva', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('valor', models.IntegerField(verbose_name=10)),
                ('id_depto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva', to='projects.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='reservaPresencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaPresencial', to='projects.cliente')),
                ('id_recepcionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaPresencial', to='projects.recepcionista')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaPresencial', to='projects.reserva')),
            ],
            options={
                'verbose_name': 'Reserva Presencial',
                'ordering': ['id_cliente', 'id_reserva', 'id_recepcionista'],
            },
        ),
    ]
