# Generated by Django 5.2 on 2025-05-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_administrador_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='cant_banos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='cant_dormitorios',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='cant_personas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='num_depto',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='piso',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='valor_dia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cant_personas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='valor_total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reservaonline',
            name='cant_personas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reservaonline',
            name='valor_total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reservapresencial',
            name='cant_personas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reservapresencial',
            name='valor_total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tiposervicioadicional',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
