# Generated by Django 5.2 on 2025-05-01 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_departamento_administrador_cliente_personalaseo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='num_rut',
            field=models.CharField(editable=False, max_length=15, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id_checkin', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('tipo_reserva', models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online')], max_length=10)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkIn', to='projects.cliente')),
                ('id_recepcionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkIn', to='projects.recepcionista')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkIn', to='projects.reserva')),
            ],
            options={
                'verbose_name': 'Check In',
                'ordering': ['id_cliente', 'id_reserva', 'id_recepcionista'],
            },
        ),
        migrations.CreateModel(
            name='ReservaOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaOnline', to='projects.cliente')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaOnline', to='projects.reserva')),
            ],
            options={
                'verbose_name': 'Reserva Online',
                'ordering': ['id_cliente', 'id_reserva'],
            },
        ),
    ]
