# Generated by Django 5.2 on 2025-06-01 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_view_resumen_reserva'),
    ]

    operations = [
        
    ]
