# Generated by Django 5.2 on 2025-06-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_view_resumen_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='re_password',
        ),
        migrations.AlterField(
            model_name='departamento',
            name='imagen',
            field=models.ImageField(upload_to='departamentos/'),
        ),
    ]
