# Generated by Django 5.2 on 2025-05-04 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_departamento_cant_banos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservapresencial',
            name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='reservapresencial',
            name='id_recepcionista',
        ),
        migrations.RemoveField(
            model_name='reservapresencial',
            name='id_reserva_presencial',
        ),
        migrations.DeleteModel(
            name='ReservaOnline',
        ),
        migrations.DeleteModel(
            name='ReservaPresencial',
        ),
    ]
