# Generated by Django 5.2 on 2025-06-02 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_persona_re_password'),
        ('projects', '0003_remove_persona_re_password_alter_departamento_imagen'),
    ]

    operations = [
    ]
