# Generated by Django 5.2 on 2025-05-01 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_persona_num_rut_checkin_reservaonline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id_prueba', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('tipo_reserva', models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online')], max_length=10)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prueba', to='projects.cliente')),
                ('id_recepcionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prueba', to='projects.recepcionista')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prueba', to='projects.reserva')),
            ],
            options={
                'verbose_name': 'Prueba',
                'ordering': ['id_cliente', 'id_reserva', 'id_recepcionista'],
            },
        ),
    ]
