# Generated by Django 5.2 on 2025-05-04 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_reservapresencial_id_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='estado_reserva',
            new_name='tipo_reserva',
        ),
    ]
