# Generated by Django 5.2 on 2025-05-01 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_prueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
