# Generated by Django 5.2 on 2025-05-01 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_delete_prueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id_arriendo', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('id_checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriendo', to='projects.checkin')),
            ],
            options={
                'verbose_name': 'Arriendo',
            },
        ),
    ]
