# Generated by Django 5.2 on 2025-05-01 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_arriendo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioAdicional',
            fields=[
                ('id_servicio', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('cant_personas', models.IntegerField(blank=True, verbose_name=2)),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField()),
                ('valor_servicio', models.IntegerField(verbose_name=10)),
            ],
            options={
                'verbose_name': 'Servicio Adicional',
            },
        ),
        migrations.CreateModel(
            name='TipoServicioAdicional',
            fields=[
                ('id_tipo_servicio', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('valor_servicio', models.IntegerField(verbose_name=10)),
            ],
            options={
                'verbose_name': 'Tipo Servicio Adicional',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('forma_de_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], max_length=20)),
                ('total_pago', models.IntegerField(verbose_name=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('estado_pago', models.BooleanField(default=False)),
                ('id_arriendo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='projects.arriendo')),
            ],
            options={
                'verbose_name': 'Pago',
            },
        ),
        migrations.CreateModel(
            name='DetalleServicios',
            fields=[
                ('id_servicio_extra', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('id_arriendo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalleServicios', to='projects.arriendo')),
                ('id_servicio_adicional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalleServicios', to='projects.servicioadicional')),
            ],
            options={
                'verbose_name': 'Detalle Servicios',
            },
        ),
        migrations.AddField(
            model_name='servicioadicional',
            name='id_tipo_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipoServicioAdicional', to='projects.tiposervicioadicional'),
        ),
    ]
