# Generated by Django 5.2 on 2025-06-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_departamento_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrador',
            old_name='id_persona',
            new_name='persona',
        ),
        migrations.RenameField(
            model_name='arriendo',
            old_name='id_checkIn',
            new_name='checkIn',
        ),
        migrations.RenameField(
            model_name='checkin',
            old_name='id_cliente',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='checkin',
            old_name='id_recepcionista',
            new_name='recepcionista',
        ),
        migrations.RenameField(
            model_name='checkin',
            old_name='id_reserva',
            new_name='reserva',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='id_persona',
            new_name='persona',
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='id_arriendo',
            new_name='arriendo',
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='id_recepcionista',
            new_name='recepcionista',
        ),
        migrations.RenameField(
            model_name='personalaseo',
            old_name='id_persona',
            new_name='persona',
        ),
        migrations.RenameField(
            model_name='recepcionista',
            old_name='id_persona',
            new_name='persona',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='id_cliente',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='id_departamento',
            new_name='departamento',
        ),
        migrations.RenameField(
            model_name='servicioadicionalconsumido',
            old_name='id_arreindo',
            new_name='arreindo',
        ),
        migrations.RenameField(
            model_name='servicioadicionalconsumido',
            old_name='id_tipo_servicio_adicional',
            new_name='tipo_servicio_adicional',
        ),
        migrations.AddField(
            model_name='persona',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
