# Generated by Django 5.2 on 2025-06-04 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='descripcion',
        ),
    ]
