# Generated by Django 5.2 on 2025-05-02 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_administrador_id_administrador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservaonline',
            name='id',
        ),
        migrations.AlterField(
            model_name='reservaonline',
            name='id_reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='reservaOnline', serialize=False, to='projects.reserva'),
        ),
    ]
