# Generated by Django 5.2 on 2025-06-05 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_administrador_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.rol'),
        ),
    ]
