# Generated by Django 5.2 on 2025-06-21 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_reserva_pagado_alter_persona_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcionista',
            name='persona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.persona'),
            preserve_default=False,
        ),
    ]
