# Generated by Django 5.2 on 2025-06-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_recepcionista_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='cert_antecedentes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='administrador',
            name='fotoAdministrador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='administrador',
            name='profesión',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='administrador',
            name='sueldo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='tipo_prevision',
            field=models.CharField(default='Fonasa', max_length=50),
            preserve_default=False,
        ),
    ]
