# Generated by Django 5.2 on 2025-06-22 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_administrador_cert_antecedentes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='cert_antecedentes',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='profesión',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='sueldo',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='tipo_prevision',
        ),
        migrations.AddField(
            model_name='administrador',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.turno'),
        ),
        migrations.AddField(
            model_name='personalaseo',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.turno'),
        ),
        migrations.AddField(
            model_name='recepcionista',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.turno'),
        ),
    ]
