# Generated by Django 5.2 on 2025-06-22 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_horasextras_prevision_sueldo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prevision',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='prevision',
            name='fecha_modificacion',
        ),
    ]
