# Generated by Django 5.2 on 2025-06-22 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_remove_prevision_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='horasextras',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='sueldo',
            name='fecha_modificacion',
        ),
    ]
