# Generated by Django 5.2 on 2025-06-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_remove_contrato_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Isapre',
            fields=[
                ('id_isapre', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('porcentaje', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TramoFonasa',
            fields=[
                ('id_tramo_fonasa', models.AutoField(primary_key=True, serialize=False)),
                ('tramo', models.CharField(max_length=20, unique=True)),
                ('porcentaje', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
