# Generated by Django 5.2 on 2025-06-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_isapre_tramofonasa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramofonasa',
            name='porcentaje',
        ),
        migrations.AddField(
            model_name='tramofonasa',
            name='descripcion',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
