# Generated by Django 5.2 on 2025-06-22 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_remove_tramofonasa_porcentaje_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isapre',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='isapre',
            name='porcentaje',
        ),
    ]
