# Generated by Django 5.2 on 2025-06-22 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_remove_isapre_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TramoFonasa',
        ),
        migrations.AddField(
            model_name='administrador',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.contrato'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='provision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.prevision'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='sueldo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.sueldo'),
        ),
    ]
