# Generated by Django 5.2 on 2025-07-04 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_delete_tramofonasa_administrador_contrato_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrador',
            old_name='provision',
            new_name='prevision',
        ),
        migrations.RenameField(
            model_name='sueldo',
            old_name='monto',
            new_name='sueldo',
        ),
        migrations.AddField(
            model_name='horasextras',
            name='dia_hora_extra',
            field=models.CharField(blank=True, choices=[('MON', 'Lunes'), ('TUE', 'Martes'), ('WED', 'Miércoles'), ('THU', 'Jueves'), ('FRI', 'Viernes'), ('SAT', 'Sábado'), ('SUN', 'Domingo')], max_length=3, null=True, verbose_name='Día de hora extra'),
        ),
        migrations.AddField(
            model_name='sueldo',
            name='horasExtras',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.horasextras'),
        ),
        migrations.AddField(
            model_name='sueldo',
            name='profesion',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='sueldo',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.rol'),
        ),
        migrations.AlterField(
            model_name='horasextras',
            name='cantidad_horas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horasextras',
            name='valor_hora',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
