# Generated by Django 5.2 on 2025-07-04 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_rename_provision_administrador_prevision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.rol'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='s_apellido',
            field=models.CharField(max_length=20, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='s_nombre',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Segundo Nombre'),
        ),
    ]
