# Generated by Django 5.2 on 2025-07-04 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_alter_persona_rol_alter_persona_s_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='cert_antecedentes',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='fotoAdministrador',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='prevision',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='profesión',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='sueldo',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='turno',
        ),
        migrations.RemoveField(
            model_name='personalaseo',
            name='turno',
        ),
        migrations.RemoveField(
            model_name='recepcionista',
            name='turno',
        ),
    ]
