# Generated by Django 5.2 on 2025-07-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_remove_administrador_cert_antecedentes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='imagen_perfil',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
