# Generated by Django 5.2 on 2025-07-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_alter_persona_imagen_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='imagen_perfil',
            field=models.URLField(blank=True, null=True),
        ),
    ]
