"""
Django settings for bahia_bonita project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import psycopg2
from dotenv import load_dotenv
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8k6jf&++_9g#-+583(o7+6l8*8s9!-33i7k$#gjv6od8y&z2yq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'projects',
    'rest_framework',
    
    
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',    
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bahia_bonita.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "projects" / "templates"], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bahia_bonita.wsgi.application'
LOGIN_REDIRECT_URL = 'index'  # Redirigir después de iniciar sesión
LOGOUT_REDIRECT_URL = 'index'  # Redirigir después de cerrar sesión

LOGIN_URL = '/login/'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres.xproyajltrkqnqtgykcl',
        'PASSWORD': '*Yt7pb2iLQSt*@Z',
        'HOST': 'aws-0-us-west-1.pooler.supabase.com',
        'PORT': '5432',
        
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

import os

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Transbank settings
TRANSBANK_API_URL = "https://webpay3gint.transbank.cl"  # o producción
TRANSBANK_COMMERCE_CODE = "597055555532"
TRANSBANK_API_KEY = "579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C"

#settings url_api registro
URL_API_REGISTRO = "http://localhost:8000/api/persona/"
URL_API_LOGIN = "http://localhost:8000/api/login/"
URL_API_CONTACTO = "http://localhost:8000/api/contacto/"

URL_API_ADDDEPTO = "http://localhost:8000/api/depto/"
URL_API_LIST_DEPTO = "http://localhost:8000/api/depto/"
URL_API_CLIENTE = "http://localhost:8000/api/cliente/"
URL_API_RESERVA = "http://localhost:8000/api/reservas/"

# clave api rapidAPI
# RAPIDAPI_KEY = "265ae1d89fmsh43cb1b76b5dda66p19835fjsnd2f11953b0d6"



MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

##servidor SMTP de gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'contactobahiabonita@gmail.com'
EMAIL_HOST_PASSWORD = 'skvh nzlq chts pziw'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_CONTACTO = 'contactobahiabonita@gmail.com'
